import React, {useState, useEffect} from 'react';

import {Loader, Card, FormField} from '../components/index';


const RenderCards = ({data,title}) => {
if(data?.length > 0 ){
  return data.map((post) => 
  <Card key={post._id} 
  {...post}/>)
}
 return (
  <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>
      {title}
  </h2>
 )
}



const Home = () => {
  const [loading,setLoading] = useState(false);
  const [allPosts,setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("")
  return (
   <section className='max-w-7xl mx-auto' >
    <div>
      <h1 className='font-extrabold text-[#222328] text-[32px]'> 
        Community Showcase
        <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>
           Browse through awesome images generated by DALL-E AI
        </p>
      </h1>
    </div>
    <div className='mt-16'>
    <FormField/>
    </div>

    <div className='mt-10'>
         {loading ? (
          <div className='flex justify-center items-center'>
            <Loader/>
            </div>
         ) : 
         <>
          {searchText && (
            <h3 className='font-medium text-[#666e75] text-xl mb-3'>
               Showing Results for <span className='text-[#222338]'>
                       {searchText}
               </span>
            </h3>
          )}
          <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap 3'>
               {searchText ? (
                <RenderCards data={[]}
                             title="No Search Results Found" />
               ) :
              
               <RenderCards
                 data={[]}
                title="No Posts found"
        
               />
               }
          </div>
         </>
        }
    </div>
   </section>
  )
}

export default Home